name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=3.4.5
  - seaborn
  - pandas
  - pip
  - pandas-profiling
  - pyarrow
  - pip:
      - wandb
  

  dependencies:
  - jupyterlab
  - pandas
  - pyarrow
  - wandb